name: SoundDetect
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.0=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hc20f281_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - zlib=1.3.1=h2466b09_2
  - pip:
      - cffi==2.0.0
      - cryptography==46.0.3
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - mysql-connector-python==9.5.0
      - networkx==3.3
      - numpy==2.1.2
      - pillow==11.3.0
      - pycparser==2.23
      - pygame==2.6.1
      - pymysql==1.1.2
      - sympy==1.14.0
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - typing-extensions==4.15.0
prefix: D:\Anacode\envs\SoundDetect
